# 💡 提示：请根据您的需求选择合适的沟通渠道：
# - 一般性问题或讨论 → 使用 GitHub Discussions
# - 查看项目文档 → 访问 Wiki
# - 提交 Bug 或功能请求 → 提交 Issue

blank_issues_enabled: false
contact_links:
  - name: ❓ 问题和讨论
    url: https://github.com/hjx-25pc1/hjx-25pc1.github.io/discussions
    about: 如有一般性问题，请使用 GitHub Discussions。
  - name: 📖 查看文档
    url: https://github.com/hjx-25pc1/hjx-25pc1.github.io/wiki
    about: 请先查阅我们的项目文档。
